(defun config (x) (load (concat "~/.emacs.d/" x)))

(config "init-package")
(config "init-server")
(config "deinit-annoyances")
(config "init-theme")
(config "init-company")
(config "init-magit")
(config "init-evil")
(config "init-idris")
(config "init-haskell")
(config "init-scala")
(config "init-popwin")
